name: Gitee repos mirror periodic job
on:
# 如果需要PR触发把push前的#去掉
# push:
  schedule:
    # 每天北京时间9点跑
    - cron:  '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/gitee-mirror-action@v0.01
      #代表我们用的仓库，不用同步
      with:
        # 必选，需要同步的Github用户（源）
        src: github/钟小龙
        # 必选，需要同步到的Gitee的用户（目的）
        dst: gitee/钟小龙
        # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
        dst_key: ${{ ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMozR42v81h4u2QMprEa5ND8fqS94UgVZqszfRRvtBTJ 812090584@qq.com }}
        # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
        dst_token:  ${{ e2642da63f88d1c0a2de2e511f809598 }}
        # 如果是组织，指定组织即可，默认为用户user
        account_type: user
        # 还有黑、白名单，静态名单机制，可以用于更新某些指定库
        # static_list: repo_name
        # black_list: 'repo_name,repo_name2'
        # white_list: 'repo_name,repo_name2'
